image: Visual Studio 2017

skip_commits:
  files:
    - nuspec/*
    - tools/*
    - '**/*.cake'
    - '**/*.md'
    - '**/*.yml'

init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1 -settings_skipverification=true -target AppVeyor

test: off